version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    environment:
      - NODE_ENV=development

